CREATE TABLE [dbo].[Company]
(
	[Id] INT NOT NULL IDENTITY (1,1) PRIMARY KEY, 
    [Name] NVARCHAR(50) NOT NULL, 
    [LastModifiedOn] DATETIME NOT NULL DEFAULT GETUTCDATE(), 
    [DeletedOn] DATETIME NULL DEFAULT NULL
)
